server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myfamily
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL95Dialect

    show-sql: true